# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003e86b1117557bc9c01576034cf4e30da843cb08b3460b2ccc57bb96880b695a12a5cbef0c049f6b25f45f56ad5bbdb4572d4ed4eda7cffc852bec5efc3909b

test:
  secret_key_base: 89b076041731ea4c38b9d62ea7facc84902611add8b67873d370cffc082e5cb7b8a40ba6b5c5e18830172b57940f44b5f12b4aee21c2cced71536ffbefd077f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
